version: '3'
services:
  postgres:
    restart: always
    image: jhorn00/findash-pg:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: jhorn00/findash-nginx:latest
    ports:
      - '80:80'
  api:
    restart: on-failure:100
    image: jhorn00/findash-server:latest
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    restart: on-failure:100
    stdin_open: true
    image: jhorn00/findash-client:latest
